# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Setting PATH for Python 3.5
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

export EDITOR="/Applications/Emacs.app/Contents/MacOS/Emacs"

#alias emacs="/usr/local/Cellar/emacs/24.5/Emacs.app"

source ~/.git-completion.bash
source ~/.git-prompt.sh
alias gco='git co'
alias gci='git ci'
alias grb='git rb'


# MacPorts Installer addition on 2015-10-31_at_15:21:08: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

# Custom (aka fuckin' brilliant) command prompt. Shows git branch if in git repo. \e sets the color of the branch to 0;31 (RED). Ensure you escape correctly (http://stackoverflow.com/questions/342093/ps1-line-wrapping-with-colours-problem)
export PS1='\h:\W \u\[\e[31m\]$(__git_ps1 "[%s]")\[\e[m\]\$ '

# Make the display even more awesome by color coding different types of files. For ref: http://www.mkyong.com/mac/add-color-to-the-bash-terminal-in-mac-os-x/
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

